name: mobile
description: Africa Tourism Intelligence Platform Mobile App
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  get_it: ^9.2.0
  dio: ^5.9.1
  shared_preferences: ^2.5.4
  internet_connection_checker: ^3.0.1
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
